spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/budgetmanager
    username: postgres
    password: password

  liquibase:
    enabled: 'true'
    change-log: classpath:/db/changelog/changelog.xml

server:
  port: 8080
  error:
    include-message: always

rsa:
  private-key: classpath:certs/privkey.pem
  public-key: classpath:certs/pubkey.pem

logging:
  level:
    org:
      springframework:
        security: DEBUG