spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/budgetmanager
    username: postgres
    password: password

  liquibase:
    enabled: 'true'
    change-log: classpath:/db/changelog/changelog.xml